<div class="row-fluid">
<div class="span2">
    <div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header">Actions</li>
        <li class="active"><a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)); ?>"><i class="icon-list-alt icon-white"></i> Issues</a></li>
    </ul>
    </div>
</div>
<div class="span10">
<table class="table table-striped table-condensed">
<thead>
<tr>
    <th><input type="checkbox" /></th>
    <th><a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.$offset.'&sort=repeats'; ?>">#</a></th>
    <th><a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.$offset.'&sort=id'; ?>">ID</a></th>
    <th><a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.$offset.'&sort=date'; ?>">Date</a></th>
    <th><a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.$offset.'&sort=name'; ?>">Rule</a></th>
    <th><a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.$offset.'&sort=fullUrl'; ?>">Origin</a></th>
    <th></th>
</tr>
</thead>
<tbody>
<?php
foreach ($issues as $issue) {
    echo '<tr>
             <td><input type="checkbox" /></td>
             <td><span class="badge">'.$issue->getNrOfOccurences().'</span></td>
             <td><a href="'.$this->url('zs-console/issue', array('serverId' => $server, 'issueId'=>$issue->getId())).'">'.$issue->getId().'</a></td>
             <td>'.$issue->getDate().'</td>
             <td>'.$issue->getRule().'</td>
             <td><span title="'.$issue->getOrigin().'">'.substr($issue->getOrigin(), 0, 80).'</td>
             <td><div class="btn-group">
                    <a class="btn btn-mini btn-danger" href="'.$this->url('zs-console/close-issue', array('serverId' => $server, 'issueId'=>$issue->getId())).'"><i class="icon-trash icon-white"></i></a>
                    <a class="btn btn-mini"><i class="icon-repeat "></i></a>
                    <a class="btn btn-mini btn-inverse"><i class="icon-filter icon-white"></i></a>
            </div></td>
         </tr>';
}
?>
<tr>
    <td><i class="icon-tasks"></i></td>
    <td colspan="6">
        <a class="btn btn-mini btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
        <a class="btn btn-mini"><i class="icon-repeat"></i> Reopen</a>
        <a class="btn btn-mini btn-inverse"><i class="icon-filter icon-white"></i> Ignore</a>
    </td>
</tr>
</tbody>
</table>

<ul class="pager">
<li class="previous">
<a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.max(($offset-$limit), 0).'&sort='.$sort; ?>">&larr; Previous</a>
</li>
<li class="next">
<a href="<?php echo $this->url('zs-console/issues', array('serverId' => $server)).'?offset='.($offset+$limit).'&sort='.$sort; ?>">Next &rarr;</a>
</li>
</ul>
</div>
</div>